name: njf_bi
version: "1.0.0"
config-version: 2
profile: njf_bi

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  njf_bi:
    staging:
      +materialized: view
      +schema: staging
